{{- $localTls := (get (.Values.local | default dict) "tls") | default dict }}
{{- $localTlsCrt := (get $localTls "crt") | default "" }}
{{- $localTlsKey := (get $localTls "key") | default "" }}
{{- if and .Values.local .Values.ingress.tls.secretName $localTlsCrt $localTlsKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $localTlsCrt | b64enc | quote }}
  tls.key: {{ $localTlsKey | b64enc | quote }}
{{- end }}
