apiVersion: v1
kind: ConfigMap
metadata:
  name: ellf-worker-types
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ellf.labels" . | nindent 4 }}
data:
  worker-types.json: {{ .Values.workerTypes | toJson | quote }}
